### ISSUE TITLE
A timeout occured while waiting for a WSL integration agent to become ready

### ISSUE THREAD

**Issue by albanoMendes** [docker/for-win#13395]
- [x] I have tried with the latest version of Docker Desktop
  - [x ] I have tried disabling enabled experimental features
  - [ x] I have uploaded Diagnostics
  - Diagnostics ID: 4849C103-7519-4ABD-ACCB-8746018BE04C/20230413004833

```[tasklist]
### Tasks
- [ x] Add a draft title or issue reference here
```

```[tasklist]
### Tasks
- [x] Add a draft title or issue reference here
```

```[tasklist]
### Tasks
- [x] Add a draft title or issue reference here
```

```[tasklist]
### Tasks
- [x] Add a draft title or issue reference here
```

```[tasklist]
### Tasks
- [x] Add a draft title or issue reference here
```

4849C103-7519-4ABD-ACCB-8746018BE04C/20230413004833

### Information

  - Windows Version: Windows 10 Pro  version：22H2
  - Docker Desktop Version:  4.18.0.0
  - WSL2 or Hyper-V backend?  WLS2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No

```[tasklist]
### Tasks
- [x] Add a draft title or issue reference here
```

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by LeviPesin** [comment]
Solution described in https://github.com/docker/for-win/issues/13426.
